# Generated by Django 5.0 on 2023-12-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('short_description', models.TextField(verbose_name='краткое описание')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('type_link', models.CharField(choices=[('website', 'website'), ('book', 'book'), ('article', 'article'), ('music', 'music'), ('video', 'video')], verbose_name='тип ссылки')),
                ('preview', models.ImageField(upload_to='bookmarks', verbose_name='картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('complation', models.ManyToManyField(to='complation.complation', verbose_name='коллекция')),
            ],
        ),
    ]
