# Generated by Django 5.0 on 2023-12-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='bookmarks', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='type_link',
            field=models.CharField(choices=[('website', 'website'), ('book', 'book'), ('article', 'article'), ('music', 'music'), ('video', 'video')], default='website', verbose_name='тип ссылки'),
        ),
    ]
