# Generated by Django 5.0 on 2023-12-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_alter_bookmark_preview_alter_bookmark_type_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='preview',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='type_link',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='link',
            new_name='url',
        ),
    ]
