# Generated by Django 5.0 on 2023-12-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_rename_preview_bookmark_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='short_description',
            new_name='description',
        ),
    ]
