# Generated by Django 5.0 on 2023-12-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_rename_short_description_bookmark_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='bookmarks', verbose_name='картинка'),
        ),
    ]
